<script lang="ts">
	import { onMount } from 'svelte';

	import { genreToBPM, shuffle } from '$lib/conversion';
	import { playlists } from './stores';

	export let data;

	let playlist;
	let music;
	let authorised = false;
	let tracks = [];
	let progress = 0;
	let total = 0;
	let targetDuration = 30;
	let playlistName = 'Pacesetter';

	enum State {
		READY = 1,
		PLAYLISTS_LOADING = 2,
		PLAYLISTS_LOADED = 3,
		PLAYLIST_SELECTED = 4,
		TRACKS_LOADING = 5,
		TRACKS_LOADED = 6,
		PLAYLIST_SAVING = 7,
		PLAYLIST_SAVED = 8
	}

	let state: State = State.READY;

	$: targetDurationInMS = targetDuration * 60000;

	const getAllPlaylists = async (accum, offset = 0) => {
		try {
			const boop = await music.api.library.playlists(null, { offset });
			if (!boop.length) {
				return accum;
			}
			accum = [...accum, ...boop];
			return getAllPlaylists(accum, offset + 25);
		} catch (error) {
			console.log('error');
			return accum;
		}
	};

	onMount(async () => {
		music = MusicKit.getInstance();
		await music.authorize();
		authorised = true;
		state = State.PLAYLISTS_LOADING;
		$playlists = await getAllPlaylists([]);
		state = State.PLAYLISTS_LOADED;
	});

	const createPlaylist = async () => {
		const body = {
			attributes: {
				description: `A playlist generated by Pacesetter on ${new Date().toLocaleDateString()}`,
				name: playlistName
			}
		};

		const req = await fetch('https://api.music.apple.com/v1/me/library/playlists', {
			method: 'post',
			body: JSON.stringify(body),
			headers: {
				Authorization: `Bearer ${data.jwt}`,
				'music-user-token': music.musicUserToken,
				'Content-Type': 'application/json'
			}
		});

		const boop = await req.json();

		await addTracksToPlaylist(boop.data[0].id);
		console.log('createPlaylist boop', boop);
	};

	const addTracksToPlaylist = async (playlistID) => {
		const body = {
			data: tracks.map((track) => ({ id: track.id, type: track.type }))
		};

		const req = await fetch(
			`https://api.music.apple.com/v1/me/library/playlists/${playlistID}/tracks`,
			{
				method: 'post',
				body: JSON.stringify(body),
				headers: {
					Authorization: `Bearer ${data.jwt}`,
					'music-user-token': music.musicUserToken,
					'Content-Type': 'application/json'
				}
			}
		);

		const boop = await req.json();
		return boop;
	};

	const trimToDuration = (tracks) => {
		console.log('tracks', tracks);
		// Shuffle everything
		// Reduce until time met
		const shuffledTracks = shuffle([...tracks]);
		const x = shuffledTracks.reduce(
			(accum, track) => {
				if (accum.duration < targetDurationInMS) {
					return {
						tracks: [track, ...accum.tracks],
						duration: accum.duration + track.attributes.durationInMillis
					};
				}
				return accum;
			},
			{ tracks: [], duration: 0 }
		);
		console.log('x', x);
		return x.tracks;
	};

	const handleSelectPlaylist = async (event) => {
		await music.authorize();

		playlist = await music.api.library.playlist(event.target.value);
		state = State.PLAYLIST_SELECTED;
		tracks = getTracksFromPlaylist(playlist);
		tracks = trimToDuration(tracks);

		total = tracks.length;
		state = State.TRACKS_LOADING;

		const promises = tracks.map(async (track) => {
			const bpm = await searchTrack(track);
			return {
				...track,
				isIndeterminate: !bpm.tempo,
				tempo: Number(bpm.tempo) || genreToBPM(track.attributes.genreNames[0])
			};
		});

		tracks = Promise.all(promises).then((results) => {
			tracks = results
				.sort((a, b) => a.tempo - b.tempo)
				.reduceRight((acc, val, i) => {
					return i % 2 === 0 ? [...acc, val] : [val, ...acc];
				}, []);

			state = State.TRACKS_LOADED;
		});

		promises.forEach((p) => p.then(() => (progress += 1)));
	};

	const getTracksFromPlaylist = (playlist) => {
		return playlist.relationships.tracks.data;
	};

	const searchTrack = async (track) => {
		const x = await fetch(
			`/bpm?track=${encodeURIComponent(track.attributes.name)}&artist=${encodeURIComponent(
				track.attributes.artistName
			)}`
		);

		const res = await x.json();

		return res;
	};
</script>

<svelte:head>
	<meta name="apple-music-developer-token" content={data.jwt} />
	<meta name="apple-music-app-name" content="Pacesetter" />
	<meta name="apple-music-app-build" content="1978.4.1" />
	<script src="https://js-cdn.music.apple.com/musickit/v1/musickit.js"></script>
</svelte:head>

<main class="container">
	<h1>Welcome to Pacesetter</h1>
	{#if authorised}
		<button id="apple-music-unauthorize">Logout</button>

		<label for="targetDuration">Target duration</label>
		<input
			type="text"
			id="targetDuration"
			name="targetDuration"
			placeholder="Time in minutes"
			bind:value={targetDuration}
			required
		/>
		<small>Enter the number of minutes you want the playlist to last.</small>
	{:else}
		<button id="apple-music-authorize">Login</button>
	{/if}

	{#if state === State.PLAYLISTS_LOADED}
		<details role="list">
			<summary aria-haspopup="listbox">
				{playlist?.attributes?.name || 'Select playlist to analyse'}
			</summary>
			<ul role="listbox">
				{#each $playlists as playlist}
					<li>
						<label for={playlist.id}>
							<input
								type="radio"
								id={playlist.id}
								name="playlistID"
								value={playlist.id}
								on:change={handleSelectPlaylist}
							/>
							{playlist.attributes.name}
						</label>
					</li>
				{/each}
			</ul>
		</details>
	{/if}

	{#if state === State.PLAYLISTS_LOADING}
		<p aria-busy="true">Loading your playlists&hellip;</p>
	{/if}
	{#if state === State.TRACKS_LOADING}
		<progress value={progress} max={total} />
	{/if}

	{#if state === State.TRACKS_LOADED}
		<ol>
			{#each tracks as track}
				<li>
					{track.attributes.name}
					<small>
						({track.tempo || ''}{#if track.isIndeterminate}<span data-tooltip="Estimated BPM"
								>*</span
							>{/if})
					</small>
				</li>
			{/each}
		</ol>

		<label for="playlistName">Name your playlist</label>
		<input
			type="text"
			id="playlistName"
			name="playlistName"
			placeholder="Time in minutes"
			bind:value={playlistName}
		/>

		<input role="button" type="submit" value="Save playlist" on:click={createPlaylist} />
		<a class="secondary" data-sveltekit-reload href="/" role="button">Start over</a>
	{/if}
</main>
